[package]
name = "phase-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
clap = { version = "4.5.38", features = ["derive"] }
faer = "0.22.6"
float-pretty-print = "0.1.1"
logos = "0.15.0"
num-complex = "0.4.6"
pretty = "0.12.4"
winnow = "0.7.10"
