gate I = id,
gate Z = if let |1> then -1,
gate X = if let |-> then -1,
gate S = sqrt(Z),
gate Sdag = S ^ -1,
gate V = sqrt(X),
gate T = sqrt(S),
gate Y = if let S . |-> then -1,
gate myH = if let sqrt(sqrt(Y)) . |1> then -1,
gate CZ = if let |11> then -1,
gate CX = if let |1> x id then X,
gate Toff = if let |1> x id2 then CX,
gate XC = if let |-1> then -1,
gate Swap = if let CX then XC,

Y; Z